#!/bin/bash
#
# orpheus.sh by Stefan Tomanek <stefan.tomanek@wertarbyte.de>
#              http://wertarbyte.de/tartarus.shtml
#
# This script pulls single files from the backup archives
# It uses list files generated by tartarus to find the archive
# containing the most recent version of a file
#
# WARNING This is still highly experimental!

CONFIG=$1
REQUEST=$2

. $CONFIG

ARCHIVES=$(curl -s -u ${STORAGE_FTP_USER}:${STORAGE_FTP_PASSWORD} --ftp-ssl -k ftp://${STORAGE_FTP_SERVER}/ -l)

awk -vREQUEST="$REQUEST" '
    substr($11,2) == REQUEST {
        n=split(FILENAME, T, "/");
        LISTNAME=T[n];
        split(LISTNAME, A, ".");
        PROFILE=A[1];
        DATE=A[2];
        print PROFILE, DATE, substr($11,2);
    }' "${FILE_LIST_DIRECTORY}"/*.*.list | \
    sort -r | head -n1 | \

    while read PROFILE DATE FILENAME; do
        echo "$ARCHIVES" | grep "^tartarus-${PROFILE}-${DATE}[.-]"
        # FIXME&TODO Detect archive format, encryption and compression
        #curl -s -u ${STORAGE_FTP_USER}:${STORAGE_FTP_PASSWORD} --ftp-ssl -k ftp://${STORAGE_FTP_SERVER}/${ARCHIVE} | \
        #gpg --decrypt | \
        #afio -v -P bzip2 -Z -y "$REQUEST" -i -
    done
